Use virtualenv instead of user pip
pretalx/ansible-pretalx pull request #44
Opened 2023-09-10 12:40 UTC by johanvdw

I think it is cleaner to use virtualenv instead of a pip --user:
* different instances use their own environment, which is nice in case of upgrades or plugin installs
* at least in debian, pip is actively telling you not to use it, unless you specify --break-system-packages
```
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

I'm opening as a draft PR because this will break arch compatibility.

2023-09-11 13:09 UTC, rixx requested changes
Thank you! I added a few comments. Additionally, I may be blind, but where are you setting `pretalx_python`?

2023-09-11 13:09 UTC, rixx commented on templates/pretalx.service.j2
> +WorkingDirectory={{ pretalx_virtualenv }}/lib/python{{ pretalx_system_python_version }}/site-packages/pretalx
You've removed the parametrisation (`%i`) in this service file, fundamentally changing how it's used. I don't think that's a good idea – while I personally don't run this ansible role anymore (in favour of something already using venvs, albeit more customized ones), changing the behaviour like that doesn't seem great.

2023-09-11 13:09 UTC, rixx commented on tasks/requirements_debian.yml
> +      - npm
Included this in a separate commit, just to get it merged while we talk about the rest here.

2023-09-11 13:09 UTC, rixx commented on tasks/package.yml
> +    virtualenv: "{{ pretalx_virtualenv }}"
You're using `|default(omit)` in some places but not in others, is that intentional?

2023-09-11 13:09 UTC, rixx commented on handlers/main.yml
> +- name: Compile pretalx javascript
Hmm, I don't think this is quite correct. Instead, we can just replace the `collectstatic` and `compress` commands with `rebuild` – rebuild runs collectstatic, compress and also compilemessages.

2023-09-27 20:41 UTC, johanvdw commented
I should probably have been clearer: I wanted to get some feedback about the idea of using virtualenvs in the first place, which is why I opened this PR as a draft in the first place. Will rework it a bit (and split the npm part) and open this again.

2023-09-27 20:41 UTC, closed without merging

2023-09-28 09:14 UTC, rixx commented
Yeah, absolutely in favour of using venvs in general, thank you for looking into this! Didn't mean to reject the PR entirely, just the implementation details :)